version: "3"
services:
    student_service:
        image: amundlrohne/student_service:latest
        restart: unless-stopped
        depends_on:
            - mongo
        environment:
            MONGO_URI: mongodb://mongo:27017
        ports:
            - "8080:8080"
        hostname: 172.17.0.2
    mongo:
        restart: unless-stopped
        image: mongo:4
        ports:
            - "27017:27017"
